feat: use sqlite backend
jina-ai/executor-simpleindexer pull request #41
Opened 2022-02-18 13:27 UTC by samsja

WIP : 

- [x] update code
- [ ] update docs

2022-02-18 14:54 UTC, JoanFM requested changes
Remove the `if` condition from `index` request

2022-02-18 14:56 UTC, JoanFM requested changes
Maybe a `clear` endpoint can be useful

2022-02-18 15:17 UTC, samsja commented
> 

done

2022-02-18 15:18 UTC, samsja commented
>

2022-02-18 15:20 UTC, JoanFM commented
> > Make sure to test that restarting the Flow keeps the `Indexer` with the data
> 
> Isn't it that test doing that ?
> 
> https://github.com/jina-ai/executor-simpleindexer/blob/895fb7076779aa244e5043fb3918d9cd507ca499/tests/test_simple_indexer.py#L80
> 
> 
> (well not exactly but I guess it is enough )

Make an integration test if possible

2022-02-18 15:30 UTC, samsja commented
> Maybe a `clear` endpoint can be useful

done

2022-02-18 15:34 UTC, JoanFM requested changes

2022-02-21 08:52 UTC, JoanFM requested changes

2022-02-21 08:52 UTC, JoanFM commented on tests/test_simple_indexer.py
> +    indexer.clear()
assert length before clear, to make sure it was not 0 before

2022-02-21 08:55 UTC, JoanFM approved these changes

2022-02-21 09:02 UTC, JoanFM approved these changes

2022-02-21 09:02 UTC, merged