feat: use default table name
jina-ai/executor-simpleindexer pull request #44
Opened 2022-02-25 16:53 UTC by samsja

2022-02-25 17:16 UTC, cristianmtr requested changes

2022-02-25 17:16 UTC, cristianmtr commented on executor.py
> -        table_name: Optional[str] = None,
not optional

2022-03-01 06:03 UTC, nan-wang requested changes

2022-03-01 06:03 UTC, nan-wang commented on executor.py
> +        table_name: Optional[str] = TABLE_NAME,
```suggestion
        table_name: str = 'simple_indexer_table',
```

2022-03-01 08:24 UTC, nan-wang requested changes

2022-03-01 08:24 UTC, nan-wang commented on executor.py
> +
```suggestion
```

2022-03-01 08:29 UTC, nan-wang approved these changes
LGTM👍

2022-03-01 08:29 UTC, merged